# Generated by Django 5.0.3 on 2024-03-10 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='warehouse',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='products.product'),
        ),
    ]
